### ISSUE TITLE
Add ASN and Community 

### ISSUE THREAD

**Issue by k01ek** [progala/ttl255-netbox-plugin-bgppeering#10]
Hi @progala!
Is this a tutorial only project? 
I have a plugin for BGP ASN and Community documentation. I can make PR if you plan to convert project to production use.

**Comment by progala** [comment]
Yes, for now at least, this is purely for educational purposes. Feel free to fork it if you'd like to extend the functionality.

**Comment by k01ek** [comment]
ok ,thank you!
