### ISSUE TITLE
Service 'netbox' failed to build

### ISSUE THREAD

**Issue by lordlan31** [progala/ttl255-netbox-plugin-bgppeering#4]
ttl255-netbox-plugin-bgppeering # invoke build
[...]
Step 7/15 : RUN pip install --upgrade pip  && pip install poetry
 ---> Running in daa4689763b7
Requirement already satisfied: pip in /usr/local/lib/python3.8/site-packages (20.3.3)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f991867aa30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f991867a190>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f991868f160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f991868f340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f991868f4f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pip/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3d6fdc2b20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3d6fdc2d60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3d6fdc2f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3d6faef0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3d6faef280>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/
ERROR: Could not find a version that satisfies the requirement poetry
ERROR: No matching distribution found for poetry
Service 'netbox' failed to build: The command '/bin/sh -c pip install --upgrade pip  && pip install poetry' returned a non-zero code: 1

**Comment by progala** [comment]
This looks to be a problem with connection to PyPi from your environment:

`'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3d6faef0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')'`
